<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function ubc_apsc_event_autofill_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_ubc_event_form' || $form_id == 'node_ubc_event_edit_form') {
    $form['#attached']['library'][] = 'ubc_apsc_event_autofill/autofill';
  }
}

/**
 * Implements hook_update_projects_alter(&$projects).
 * Alter the list of projects before fetching data and comparing versions.
 *
 * Hide projects from the list to avoid "No available releases found" warnings on the available updates report
 *
 * @see \Drupal\update\UpdateManager::getProjects()
 * @see \Drupal\Core\Utility\ProjectInfo::processInfoList()
 */
function ubc_apsc_event_autofill_update_projects_alter(&$projects) {
  // Hide a site-specific module from the list.
  unset($projects['ubc_apsc_event_autofill']);
}
